// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_hls_sobel_hls,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.640500,HLS_SYN_LAT=9842,HLS_SYN_TPT=none,HLS_SYN_MEM=11,HLS_SYN_DSP=0,HLS_SYN_FF=1124,HLS_SYN_LUT=3074,HLS_VERSION=2023_2}" *)

module sobel_hls (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg   [8:0] frame_address0;
reg    frame_ce0;
reg    frame_we0;
wire   [7:0] frame_q0;
reg   [8:0] frame_1_address0;
reg    frame_1_ce0;
reg    frame_1_we0;
wire   [7:0] frame_1_q0;
reg   [8:0] frame_2_address0;
reg    frame_2_ce0;
reg    frame_2_we0;
wire   [7:0] frame_2_q0;
reg   [8:0] frame_3_address0;
reg    frame_3_ce0;
reg    frame_3_we0;
wire   [7:0] frame_3_q0;
reg   [8:0] frame_4_address0;
reg    frame_4_ce0;
reg    frame_4_we0;
wire   [7:0] frame_4_q0;
reg   [8:0] frame_5_address0;
reg    frame_5_ce0;
reg    frame_5_we0;
wire   [7:0] frame_5_q0;
reg   [8:0] frame_6_address0;
reg    frame_6_ce0;
reg    frame_6_we0;
wire   [7:0] frame_6_q0;
reg   [8:0] frame_7_address0;
reg    frame_7_ce0;
reg    frame_7_we0;
wire   [7:0] frame_7_q0;
reg   [8:0] frame_8_address0;
reg    frame_8_ce0;
reg    frame_8_we0;
wire   [7:0] frame_8_q0;
reg   [11:0] output_address0;
reg    output_ce0;
reg    output_we0;
reg   [7:0] output_d0;
wire   [7:0] output_q0;
wire    grp_sobel_hls_Pipeline_1_fu_98_ap_start;
wire    grp_sobel_hls_Pipeline_1_fu_98_ap_done;
wire    grp_sobel_hls_Pipeline_1_fu_98_ap_idle;
wire    grp_sobel_hls_Pipeline_1_fu_98_ap_ready;
wire   [11:0] grp_sobel_hls_Pipeline_1_fu_98_output_r_address0;
wire    grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0;
wire    grp_sobel_hls_Pipeline_1_fu_98_output_r_we0;
wire   [7:0] grp_sobel_hls_Pipeline_1_fu_98_output_r_d0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_idle;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_idle;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready;
wire   [11:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0;
wire   [7:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0;
wire   [8:0] grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_idle;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY;
wire   [11:0] grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0;
wire   [31:0] grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA;
wire    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID;
wire   [3:0] grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP;
wire   [3:0] grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB;
wire   [0:0] grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST;
reg    grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg   [8:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state9;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg = 1'b0;
#0 grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg = 1'b0;
#0 grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg = 1'b0;
end

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_address0),
    .ce0(frame_ce0),
    .we0(frame_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0),
    .q0(frame_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_1_address0),
    .ce0(frame_1_ce0),
    .we0(frame_1_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0),
    .q0(frame_1_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_2_address0),
    .ce0(frame_2_ce0),
    .we0(frame_2_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0),
    .q0(frame_2_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_3_address0),
    .ce0(frame_3_ce0),
    .we0(frame_3_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0),
    .q0(frame_3_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_4_address0),
    .ce0(frame_4_ce0),
    .we0(frame_4_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0),
    .q0(frame_4_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_5_address0),
    .ce0(frame_5_ce0),
    .we0(frame_5_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0),
    .q0(frame_5_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_6_address0),
    .ce0(frame_6_ce0),
    .we0(frame_6_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0),
    .q0(frame_6_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_7_address0),
    .ce0(frame_7_ce0),
    .we0(frame_7_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0),
    .q0(frame_7_q0)
);

sobel_hls_frame_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 289 ),
    .AddressWidth( 9 ))
frame_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(frame_8_address0),
    .ce0(frame_8_ce0),
    .we0(frame_8_we0),
    .d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0),
    .q0(frame_8_q0)
);

sobel_hls_output_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 2500 ),
    .AddressWidth( 12 ))
output_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(output_address0),
    .ce0(output_ce0),
    .we0(output_we0),
    .d0(output_d0),
    .q0(output_q0)
);

sobel_hls_sobel_hls_Pipeline_1 grp_sobel_hls_Pipeline_1_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_hls_Pipeline_1_fu_98_ap_start),
    .ap_done(grp_sobel_hls_Pipeline_1_fu_98_ap_done),
    .ap_idle(grp_sobel_hls_Pipeline_1_fu_98_ap_idle),
    .ap_ready(grp_sobel_hls_Pipeline_1_fu_98_ap_ready),
    .output_r_address0(grp_sobel_hls_Pipeline_1_fu_98_output_r_address0),
    .output_r_ce0(grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0),
    .output_r_we0(grp_sobel_hls_Pipeline_1_fu_98_output_r_we0),
    .output_r_d0(grp_sobel_hls_Pipeline_1_fu_98_output_r_d0)
);

sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2 grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start),
    .ap_done(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done),
    .ap_idle(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_idle),
    .ap_ready(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .frame_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0),
    .frame_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0),
    .frame_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0),
    .frame_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0),
    .frame_1_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0),
    .frame_1_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0),
    .frame_1_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0),
    .frame_1_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0),
    .frame_2_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0),
    .frame_2_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0),
    .frame_2_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0),
    .frame_2_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0),
    .frame_3_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0),
    .frame_3_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0),
    .frame_3_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0),
    .frame_3_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0),
    .frame_4_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0),
    .frame_4_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0),
    .frame_4_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0),
    .frame_4_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0),
    .frame_5_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0),
    .frame_5_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0),
    .frame_5_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0),
    .frame_5_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0),
    .frame_6_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0),
    .frame_6_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0),
    .frame_6_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0),
    .frame_6_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0),
    .frame_7_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0),
    .frame_7_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0),
    .frame_7_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0),
    .frame_7_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0),
    .frame_8_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0),
    .frame_8_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0),
    .frame_8_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0),
    .frame_8_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice)
);

sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4 grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start),
    .ap_done(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done),
    .ap_idle(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_idle),
    .ap_ready(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready),
    .output_r_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0),
    .output_r_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0),
    .output_r_we0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0),
    .output_r_d0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0),
    .frame_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0),
    .frame_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0),
    .frame_q0(frame_q0),
    .frame_1_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0),
    .frame_1_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0),
    .frame_1_q0(frame_1_q0),
    .frame_2_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0),
    .frame_2_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0),
    .frame_2_q0(frame_2_q0),
    .frame_3_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0),
    .frame_3_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0),
    .frame_3_q0(frame_3_q0),
    .frame_4_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0),
    .frame_4_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0),
    .frame_4_q0(frame_4_q0),
    .frame_5_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0),
    .frame_5_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0),
    .frame_5_q0(frame_5_q0),
    .frame_6_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0),
    .frame_6_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0),
    .frame_6_q0(frame_6_q0),
    .frame_7_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0),
    .frame_7_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0),
    .frame_7_q0(frame_7_q0),
    .frame_8_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0),
    .frame_8_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0),
    .frame_8_q0(frame_8_q0)
);

sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8 grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start),
    .ap_done(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done),
    .ap_idle(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_idle),
    .ap_ready(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready),
    .M_AXIS_TREADY(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY),
    .output_r_address0(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0),
    .output_r_ce0(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0),
    .output_r_q0(output_q0),
    .M_AXIS_TDATA(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA),
    .M_AXIS_TVALID(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID),
    .M_AXIS_TKEEP(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB),
    .M_AXIS_TLAST(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST)
);

sobel_hls_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA),
    .vld_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP),
    .vld_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB),
    .vld_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

sobel_hls_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST),
    .vld_in(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_hls_Pipeline_1_fu_98_ap_ready == 1'b1)) begin
            grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready == 1'b1)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready == 1'b1)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready == 1'b1)) begin
            grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        S_AXIS_TREADY_int_regslice = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_hls_Pipeline_1_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_1_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_1_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0;
    end else begin
        frame_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_1_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_1_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0;
    end else begin
        frame_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_1_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0;
    end else begin
        frame_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_2_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_2_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0;
    end else begin
        frame_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_2_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_2_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0;
    end else begin
        frame_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_2_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0;
    end else begin
        frame_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_3_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_3_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0;
    end else begin
        frame_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_3_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_3_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0;
    end else begin
        frame_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_3_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0;
    end else begin
        frame_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_4_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_4_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0;
    end else begin
        frame_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_4_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_4_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0;
    end else begin
        frame_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_4_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0;
    end else begin
        frame_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_5_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_5_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0;
    end else begin
        frame_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_5_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_5_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0;
    end else begin
        frame_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_5_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0;
    end else begin
        frame_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_6_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_6_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0;
    end else begin
        frame_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_6_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_6_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0;
    end else begin
        frame_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_6_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0;
    end else begin
        frame_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_7_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_7_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0;
    end else begin
        frame_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_7_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_7_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0;
    end else begin
        frame_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_7_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0;
    end else begin
        frame_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_8_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_8_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0;
    end else begin
        frame_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_8_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_8_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0;
    end else begin
        frame_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_8_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0;
    end else begin
        frame_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0;
    end else begin
        frame_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        frame_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0;
    end else begin
        frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        frame_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0;
    end else begin
        frame_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        output_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_address0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        output_address0 = grp_sobel_hls_Pipeline_1_fu_98_output_r_address0;
    end else begin
        output_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        output_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_ce0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        output_ce0 = grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0;
    end else begin
        output_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_d0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        output_d0 = grp_sobel_hls_Pipeline_1_fu_98_output_r_d0;
    end else begin
        output_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_we0 = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        output_we0 = grp_sobel_hls_Pipeline_1_fu_98_output_r_we0;
    end else begin
        output_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_sobel_hls_Pipeline_1_fu_98_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign M_AXIS_TVALID_int_regslice = grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_sobel_hls_Pipeline_1_fu_98_ap_start = grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg;

assign grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start = grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg;

assign grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start = grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg;

assign grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY = (ap_CS_fsm_state8 & M_AXIS_TREADY_int_regslice);

assign grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start = grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg;

endmodule //sobel_hls
