-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_hls is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TVALID : IN STD_LOGIC;
    S_AXIS_TREADY : OUT STD_LOGIC;
    S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    M_AXIS_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_AXIS_TVALID : OUT STD_LOGIC;
    M_AXIS_TREADY : IN STD_LOGIC;
    M_AXIS_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of sobel_hls is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sobel_hls_sobel_hls,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.640500,HLS_SYN_LAT=9842,HLS_SYN_TPT=none,HLS_SYN_MEM=11,HLS_SYN_DSP=0,HLS_SYN_FF=1124,HLS_SYN_LUT=3074,HLS_VERSION=2023_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal frame_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_ce0 : STD_LOGIC;
    signal frame_we0 : STD_LOGIC;
    signal frame_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_1_ce0 : STD_LOGIC;
    signal frame_1_we0 : STD_LOGIC;
    signal frame_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_2_ce0 : STD_LOGIC;
    signal frame_2_we0 : STD_LOGIC;
    signal frame_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_3_ce0 : STD_LOGIC;
    signal frame_3_we0 : STD_LOGIC;
    signal frame_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_4_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_4_ce0 : STD_LOGIC;
    signal frame_4_we0 : STD_LOGIC;
    signal frame_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_5_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_5_ce0 : STD_LOGIC;
    signal frame_5_we0 : STD_LOGIC;
    signal frame_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_6_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_6_ce0 : STD_LOGIC;
    signal frame_6_we0 : STD_LOGIC;
    signal frame_6_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_7_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_7_ce0 : STD_LOGIC;
    signal frame_7_we0 : STD_LOGIC;
    signal frame_7_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_8_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal frame_8_ce0 : STD_LOGIC;
    signal frame_8_we0 : STD_LOGIC;
    signal frame_8_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal output_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal output_ce0 : STD_LOGIC;
    signal output_we0 : STD_LOGIC;
    signal output_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal output_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_1_fu_98_ap_start : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_ap_done : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_ap_idle : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_ap_ready : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_output_r_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_output_r_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_1_fu_98_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_idle : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_idle : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_idle : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0 : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID : STD_LOGIC;
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal regslice_both_S_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal S_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal S_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_S_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_ack_in : STD_LOGIC;
    signal M_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal M_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_hls_sobel_hls_Pipeline_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        S_AXIS_TVALID : IN STD_LOGIC;
        frame_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_ce0 : OUT STD_LOGIC;
        frame_we0 : OUT STD_LOGIC;
        frame_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_1_ce0 : OUT STD_LOGIC;
        frame_1_we0 : OUT STD_LOGIC;
        frame_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_2_ce0 : OUT STD_LOGIC;
        frame_2_we0 : OUT STD_LOGIC;
        frame_2_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_3_ce0 : OUT STD_LOGIC;
        frame_3_we0 : OUT STD_LOGIC;
        frame_3_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_4_ce0 : OUT STD_LOGIC;
        frame_4_we0 : OUT STD_LOGIC;
        frame_4_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_5_ce0 : OUT STD_LOGIC;
        frame_5_we0 : OUT STD_LOGIC;
        frame_5_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_6_ce0 : OUT STD_LOGIC;
        frame_6_we0 : OUT STD_LOGIC;
        frame_6_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_7_ce0 : OUT STD_LOGIC;
        frame_7_we0 : OUT STD_LOGIC;
        frame_7_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_8_ce0 : OUT STD_LOGIC;
        frame_8_we0 : OUT STD_LOGIC;
        frame_8_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TREADY : OUT STD_LOGIC;
        S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        frame_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_ce0 : OUT STD_LOGIC;
        frame_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_1_ce0 : OUT STD_LOGIC;
        frame_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_2_ce0 : OUT STD_LOGIC;
        frame_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_3_ce0 : OUT STD_LOGIC;
        frame_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_4_ce0 : OUT STD_LOGIC;
        frame_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_5_ce0 : OUT STD_LOGIC;
        frame_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_6_ce0 : OUT STD_LOGIC;
        frame_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_7_ce0 : OUT STD_LOGIC;
        frame_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        frame_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        frame_8_ce0 : OUT STD_LOGIC;
        frame_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        M_AXIS_TREADY : IN STD_LOGIC;
        output_r_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        M_AXIS_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_AXIS_TVALID : OUT STD_LOGIC;
        M_AXIS_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        M_AXIS_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        M_AXIS_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component sobel_hls_frame_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hls_output_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hls_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    frame_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_address0,
        ce0 => frame_ce0,
        we0 => frame_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0,
        q0 => frame_q0);

    frame_1_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_1_address0,
        ce0 => frame_1_ce0,
        we0 => frame_1_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0,
        q0 => frame_1_q0);

    frame_2_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_2_address0,
        ce0 => frame_2_ce0,
        we0 => frame_2_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0,
        q0 => frame_2_q0);

    frame_3_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_3_address0,
        ce0 => frame_3_ce0,
        we0 => frame_3_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0,
        q0 => frame_3_q0);

    frame_4_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_4_address0,
        ce0 => frame_4_ce0,
        we0 => frame_4_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0,
        q0 => frame_4_q0);

    frame_5_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_5_address0,
        ce0 => frame_5_ce0,
        we0 => frame_5_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0,
        q0 => frame_5_q0);

    frame_6_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_6_address0,
        ce0 => frame_6_ce0,
        we0 => frame_6_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0,
        q0 => frame_6_q0);

    frame_7_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_7_address0,
        ce0 => frame_7_ce0,
        we0 => frame_7_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0,
        q0 => frame_7_q0);

    frame_8_U : component sobel_hls_frame_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 289,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => frame_8_address0,
        ce0 => frame_8_ce0,
        we0 => frame_8_we0,
        d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0,
        q0 => frame_8_q0);

    output_U : component sobel_hls_output_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 2500,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => output_address0,
        ce0 => output_ce0,
        we0 => output_we0,
        d0 => output_d0,
        q0 => output_q0);

    grp_sobel_hls_Pipeline_1_fu_98 : component sobel_hls_sobel_hls_Pipeline_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sobel_hls_Pipeline_1_fu_98_ap_start,
        ap_done => grp_sobel_hls_Pipeline_1_fu_98_ap_done,
        ap_idle => grp_sobel_hls_Pipeline_1_fu_98_ap_idle,
        ap_ready => grp_sobel_hls_Pipeline_1_fu_98_ap_ready,
        output_r_address0 => grp_sobel_hls_Pipeline_1_fu_98_output_r_address0,
        output_r_ce0 => grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0,
        output_r_we0 => grp_sobel_hls_Pipeline_1_fu_98_output_r_we0,
        output_r_d0 => grp_sobel_hls_Pipeline_1_fu_98_output_r_d0);

    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104 : component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start,
        ap_done => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done,
        ap_idle => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_idle,
        ap_ready => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready,
        S_AXIS_TVALID => S_AXIS_TVALID_int_regslice,
        frame_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0,
        frame_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0,
        frame_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0,
        frame_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_d0,
        frame_1_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0,
        frame_1_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0,
        frame_1_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0,
        frame_1_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_d0,
        frame_2_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0,
        frame_2_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0,
        frame_2_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0,
        frame_2_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_d0,
        frame_3_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0,
        frame_3_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0,
        frame_3_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0,
        frame_3_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_d0,
        frame_4_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0,
        frame_4_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0,
        frame_4_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0,
        frame_4_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_d0,
        frame_5_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0,
        frame_5_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0,
        frame_5_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0,
        frame_5_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_d0,
        frame_6_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0,
        frame_6_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0,
        frame_6_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0,
        frame_6_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_d0,
        frame_7_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0,
        frame_7_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0,
        frame_7_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0,
        frame_7_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_d0,
        frame_8_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0,
        frame_8_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0,
        frame_8_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0,
        frame_8_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_d0,
        S_AXIS_TDATA => S_AXIS_TDATA_int_regslice,
        S_AXIS_TREADY => grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY,
        S_AXIS_TKEEP => S_AXIS_TKEEP_int_regslice,
        S_AXIS_TSTRB => S_AXIS_TSTRB_int_regslice,
        S_AXIS_TLAST => S_AXIS_TLAST_int_regslice);

    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125 : component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start,
        ap_done => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done,
        ap_idle => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_idle,
        ap_ready => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready,
        output_r_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0,
        output_r_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0,
        output_r_we0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0,
        output_r_d0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0,
        frame_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0,
        frame_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0,
        frame_q0 => frame_q0,
        frame_1_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0,
        frame_1_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0,
        frame_1_q0 => frame_1_q0,
        frame_2_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0,
        frame_2_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0,
        frame_2_q0 => frame_2_q0,
        frame_3_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0,
        frame_3_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0,
        frame_3_q0 => frame_3_q0,
        frame_4_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0,
        frame_4_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0,
        frame_4_q0 => frame_4_q0,
        frame_5_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0,
        frame_5_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0,
        frame_5_q0 => frame_5_q0,
        frame_6_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0,
        frame_6_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0,
        frame_6_q0 => frame_6_q0,
        frame_7_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0,
        frame_7_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0,
        frame_7_q0 => frame_7_q0,
        frame_8_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0,
        frame_8_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0,
        frame_8_q0 => frame_8_q0);

    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139 : component sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start,
        ap_done => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done,
        ap_idle => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_idle,
        ap_ready => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready,
        M_AXIS_TREADY => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY,
        output_r_address0 => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0,
        output_r_ce0 => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0,
        output_r_q0 => output_q0,
        M_AXIS_TDATA => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA,
        M_AXIS_TVALID => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID,
        M_AXIS_TKEEP => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP,
        M_AXIS_TSTRB => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB,
        M_AXIS_TLAST => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST);

    regslice_both_S_AXIS_V_data_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TDATA,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_data_V_U_ack_in,
        data_out => S_AXIS_TDATA_int_regslice,
        vld_out => S_AXIS_TVALID_int_regslice,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_data_V_U_apdone_blk);

    regslice_both_S_AXIS_V_keep_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TKEEP,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_keep_V_U_ack_in,
        data_out => S_AXIS_TKEEP_int_regslice,
        vld_out => regslice_both_S_AXIS_V_keep_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_S_AXIS_V_strb_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TSTRB,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_strb_V_U_ack_in,
        data_out => S_AXIS_TSTRB_int_regslice,
        vld_out => regslice_both_S_AXIS_V_strb_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_S_AXIS_V_last_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TLAST,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_last_V_U_ack_in,
        data_out => S_AXIS_TLAST_int_regslice,
        vld_out => regslice_both_S_AXIS_V_last_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_last_V_U_apdone_blk);

    regslice_both_M_AXIS_V_data_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TDATA,
        vld_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID,
        ack_in => M_AXIS_TREADY_int_regslice,
        data_out => M_AXIS_TDATA,
        vld_out => regslice_both_M_AXIS_V_data_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_data_V_U_apdone_blk);

    regslice_both_M_AXIS_V_keep_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TKEEP,
        vld_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy,
        data_out => M_AXIS_TKEEP,
        vld_out => regslice_both_M_AXIS_V_keep_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_M_AXIS_V_strb_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TSTRB,
        vld_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy,
        data_out => M_AXIS_TSTRB,
        vld_out => regslice_both_M_AXIS_V_strb_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_M_AXIS_V_last_V_U : component sobel_hls_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TLAST,
        vld_in => grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_last_V_U_ack_in_dummy,
        data_out => M_AXIS_TLAST,
        vld_out => regslice_both_M_AXIS_V_last_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sobel_hls_Pipeline_1_fu_98_ap_ready = ap_const_logic_1)) then 
                    grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_ready = ap_const_logic_1)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_ready = ap_const_logic_1)) then 
                    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (grp_sobel_hls_Pipeline_1_fu_98_ap_done, grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done, grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, regslice_both_M_AXIS_V_data_V_U_apdone_blk, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_sobel_hls_Pipeline_1_fu_98_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    M_AXIS_TVALID <= regslice_both_M_AXIS_V_data_V_U_vld_out;
    M_AXIS_TVALID_int_regslice <= grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TVALID;
    S_AXIS_TREADY <= regslice_both_S_AXIS_V_data_V_U_ack_in;

    S_AXIS_TREADY_int_regslice_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            S_AXIS_TREADY_int_regslice <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_S_AXIS_TREADY;
        else 
            S_AXIS_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_sobel_hls_Pipeline_1_fu_98_ap_done)
    begin
        if ((grp_sobel_hls_Pipeline_1_fu_98_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done)
    begin
        if ((grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done)
    begin
        if ((grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done)
    begin
        if ((grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    frame_1_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_1_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_1_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_address0;
        else 
            frame_1_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_1_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_1_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_1_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_ce0;
        else 
            frame_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_1_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_1_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_1_we0;
        else 
            frame_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_2_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_2_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_2_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_address0;
        else 
            frame_2_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_2_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_2_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_2_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_ce0;
        else 
            frame_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_2_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_2_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_2_we0;
        else 
            frame_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_3_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_3_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_3_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_address0;
        else 
            frame_3_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_3_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_3_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_3_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_ce0;
        else 
            frame_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_3_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_3_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_3_we0;
        else 
            frame_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_4_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_4_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_4_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_address0;
        else 
            frame_4_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_4_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_4_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_4_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_ce0;
        else 
            frame_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_4_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_4_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_4_we0;
        else 
            frame_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_5_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_5_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_5_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_address0;
        else 
            frame_5_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_5_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_5_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_5_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_ce0;
        else 
            frame_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_5_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_5_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_5_we0;
        else 
            frame_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_6_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_6_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_6_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_address0;
        else 
            frame_6_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_6_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_6_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_6_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_ce0;
        else 
            frame_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_6_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_6_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_6_we0;
        else 
            frame_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_7_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_7_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_7_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_address0;
        else 
            frame_7_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_7_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_7_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_7_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_ce0;
        else 
            frame_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_7_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_7_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_7_we0;
        else 
            frame_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_8_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_8_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_8_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_address0;
        else 
            frame_8_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_8_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_8_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_8_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_8_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_ce0;
        else 
            frame_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_8_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_8_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_8_we0;
        else 
            frame_8_we0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_address0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_address0;
        else 
            frame_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    frame_ce0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            frame_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_frame_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_ce0;
        else 
            frame_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    frame_we0_assign_proc : process(grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            frame_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_frame_we0;
        else 
            frame_we0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_sobel_hls_Pipeline_1_fu_98_ap_start <= grp_sobel_hls_Pipeline_1_fu_98_ap_start_reg;
    grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start <= grp_sobel_hls_Pipeline_VITIS_LOOP_32_1_VITIS_LOOP_33_2_fu_104_ap_start_reg;
    grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_ap_start_reg;
    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_M_AXIS_TREADY <= (ap_CS_fsm_state8 and M_AXIS_TREADY_int_regslice);
    grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start <= grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_ap_start_reg;

    output_address0_assign_proc : process(grp_sobel_hls_Pipeline_1_fu_98_output_r_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0, grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_address0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_address0 <= grp_sobel_hls_Pipeline_1_fu_98_output_r_address0;
        else 
            output_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    output_ce0_assign_proc : process(grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0, grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            output_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_56_7_VITIS_LOOP_57_8_fu_139_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_ce0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_ce0 <= grp_sobel_hls_Pipeline_1_fu_98_output_r_ce0;
        else 
            output_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_d0_assign_proc : process(grp_sobel_hls_Pipeline_1_fu_98_output_r_d0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_d0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_d0 <= grp_sobel_hls_Pipeline_1_fu_98_output_r_d0;
        else 
            output_d0 <= "XXXXXXXX";
        end if; 
    end process;


    output_we0_assign_proc : process(grp_sobel_hls_Pipeline_1_fu_98_output_r_we0, grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            output_we0 <= grp_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4_fu_125_output_r_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            output_we0 <= grp_sobel_hls_Pipeline_1_fu_98_output_r_we0;
        else 
            output_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
