// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        frame_address0,
        frame_ce0,
        frame_q0,
        frame_1_address0,
        frame_1_ce0,
        frame_1_q0,
        frame_2_address0,
        frame_2_ce0,
        frame_2_q0,
        frame_3_address0,
        frame_3_ce0,
        frame_3_q0,
        frame_4_address0,
        frame_4_ce0,
        frame_4_q0,
        frame_5_address0,
        frame_5_ce0,
        frame_5_q0,
        frame_6_address0,
        frame_6_ce0,
        frame_6_q0,
        frame_7_address0,
        frame_7_ce0,
        frame_7_q0,
        frame_8_address0,
        frame_8_ce0,
        frame_8_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [7:0] output_r_d0;
output  [8:0] frame_address0;
output   frame_ce0;
input  [7:0] frame_q0;
output  [8:0] frame_1_address0;
output   frame_1_ce0;
input  [7:0] frame_1_q0;
output  [8:0] frame_2_address0;
output   frame_2_ce0;
input  [7:0] frame_2_q0;
output  [8:0] frame_3_address0;
output   frame_3_ce0;
input  [7:0] frame_3_q0;
output  [8:0] frame_4_address0;
output   frame_4_ce0;
input  [7:0] frame_4_q0;
output  [8:0] frame_5_address0;
output   frame_5_ce0;
input  [7:0] frame_5_q0;
output  [8:0] frame_6_address0;
output   frame_6_ce0;
input  [7:0] frame_6_q0;
output  [8:0] frame_7_address0;
output   frame_7_ce0;
input  [7:0] frame_7_q0;
output  [8:0] frame_8_address0;
output   frame_8_ce0;
input  [7:0] frame_8_q0;

reg ap_idle;
reg output_r_ce0;
reg output_r_we0;
reg[8:0] frame_address0;
reg frame_ce0;
reg[8:0] frame_1_address0;
reg frame_1_ce0;
reg[8:0] frame_2_address0;
reg frame_2_ce0;
reg[8:0] frame_3_address0;
reg frame_3_ce0;
reg[8:0] frame_4_address0;
reg frame_4_ce0;
reg[8:0] frame_5_address0;
reg frame_5_ce0;
reg[8:0] frame_6_address0;
reg frame_6_ce0;
reg[8:0] frame_7_address0;
reg frame_7_ce0;
reg[8:0] frame_8_address0;
reg frame_8_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln40_fu_931_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] select_ln40_fu_955_p3;
reg   [5:0] select_ln40_reg_1802;
reg   [5:0] select_ln40_reg_1802_pp0_iter1_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter2_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter3_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter4_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter5_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter6_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter7_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter8_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter9_reg;
reg   [5:0] select_ln40_reg_1802_pp0_iter10_reg;
wire   [5:0] select_ln40_2_fu_983_p3;
reg   [5:0] select_ln40_2_reg_1810;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter1_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter2_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter3_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter4_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter5_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter6_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter7_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter8_reg;
reg   [5:0] select_ln40_2_reg_1810_pp0_iter9_reg;
wire   [5:0] add_ln41_fu_997_p2;
reg   [5:0] add_ln41_reg_1818;
reg   [5:0] add_ln41_reg_1818_pp0_iter1_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter2_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter3_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter4_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter5_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter6_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter7_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter8_reg;
reg   [5:0] add_ln41_reg_1818_pp0_iter9_reg;
reg   [4:0] tmp_42_reg_1823;
reg   [4:0] tmp_42_reg_1823_pp0_iter1_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter2_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter3_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter4_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter5_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter6_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter7_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter8_reg;
reg   [4:0] tmp_42_reg_1823_pp0_iter9_reg;
wire   [1:0] trunc_ln40_fu_1047_p1;
reg   [1:0] trunc_ln40_reg_1834;
reg   [1:0] trunc_ln40_reg_1834_pp0_iter10_reg;
wire   [1:0] trunc_ln41_fu_1051_p1;
reg   [1:0] trunc_ln41_reg_1846;
reg   [1:0] trunc_ln41_reg_1846_pp0_iter10_reg;
reg   [3:0] tmp_45_reg_2224;
wire   [7:0] trunc_ln51_fu_1747_p1;
reg   [7:0] trunc_ln51_reg_2229;
wire   [63:0] zext_ln45_5_fu_1169_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln45_10_fu_1212_p1;
wire   [63:0] zext_ln45_11_fu_1231_p1;
wire   [63:0] zext_ln45_14_fu_1273_p1;
wire   [63:0] zext_ln45_15_fu_1292_p1;
wire   [63:0] zext_ln45_17_fu_1327_p1;
wire   [63:0] zext_ln45_18_fu_1346_p1;
wire   [63:0] zext_ln45_19_fu_1365_p1;
wire   [63:0] zext_ln51_2_fu_1751_p1;
reg   [5:0] x_fu_96;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_x_load;
reg   [5:0] y_fu_100;
reg   [5:0] ap_sig_allocacmp_y_load;
reg   [11:0] indvar_flatten6_fu_104;
wire   [11:0] add_ln40_fu_937_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [7:0] grp_fu_742_p7;
wire   [7:0] grp_fu_761_p7;
wire   [7:0] grp_fu_780_p7;
wire   [7:0] grp_fu_799_p7;
wire   [7:0] grp_fu_818_p7;
wire   [7:0] grp_fu_837_p7;
wire   [7:0] grp_fu_856_p7;
wire   [7:0] grp_fu_875_p7;
wire   [7:0] grp_fu_894_p7;
wire   [0:0] icmp_ln41_fu_949_p2;
wire   [5:0] add_ln40_2_fu_963_p2;
wire   [5:0] add_ln4042_fu_969_p2;
wire   [5:0] grp_fu_991_p0;
wire   [2:0] grp_fu_991_p1;
wire   [2:0] grp_fu_1003_p1;
wire   [5:0] select_ln40_1_fu_975_p3;
wire   [5:0] mul_ln42_fu_1013_p0;
wire   [7:0] mul_ln42_fu_1013_p1;
wire   [12:0] mul_ln42_fu_1013_p2;
wire   [1:0] grp_fu_991_p2;
wire   [1:0] grp_fu_1003_p2;
wire   [5:0] mul_ln40_fu_1058_p0;
wire   [7:0] mul_ln40_fu_1058_p1;
wire   [12:0] mul_ln40_fu_1058_p2;
wire   [4:0] tmp_32_fu_1064_p4;
wire   [8:0] tmp_33_fu_1078_p3;
wire   [8:0] zext_ln45_fu_1074_p1;
wire   [5:0] mul_ln41_fu_1100_p0;
wire   [7:0] mul_ln41_fu_1100_p1;
wire   [12:0] mul_ln41_fu_1100_p2;
wire   [4:0] tmp_34_fu_1106_p4;
wire   [5:0] add_ln40_1_fu_1092_p2;
wire   [5:0] mul_ln45_fu_1129_p0;
wire   [7:0] mul_ln45_fu_1129_p1;
wire   [12:0] mul_ln45_fu_1129_p2;
wire   [4:0] tmp_35_fu_1135_p4;
wire   [8:0] tmp_36_fu_1149_p3;
wire   [8:0] zext_ln45_4_fu_1145_p1;
wire   [8:0] add_ln45_2_fu_1157_p2;
wire   [8:0] zext_ln41_1_fu_1116_p1;
wire   [8:0] add_ln45_3_fu_1163_p2;
wire   [5:0] add_ln41_1_fu_1120_p2;
wire   [5:0] mul_ln45_1_fu_1186_p0;
wire   [7:0] mul_ln45_1_fu_1186_p1;
wire   [12:0] mul_ln45_1_fu_1186_p2;
wire   [4:0] tmp_37_fu_1192_p4;
wire   [8:0] zext_ln45_9_fu_1202_p1;
wire   [8:0] add_ln45_4_fu_1206_p2;
wire   [8:0] add_ln45_1_fu_1086_p2;
wire   [8:0] add_ln45_5_fu_1225_p2;
wire   [5:0] mul_ln45_2_fu_1247_p0;
wire   [7:0] mul_ln45_2_fu_1247_p1;
wire   [12:0] mul_ln45_2_fu_1247_p2;
wire   [4:0] tmp_38_fu_1253_p4;
wire   [8:0] zext_ln45_13_fu_1263_p1;
wire   [8:0] add_ln45_6_fu_1267_p2;
wire   [8:0] add_ln45_7_fu_1286_p2;
wire   [8:0] tmp_39_fu_1308_p3;
wire   [8:0] zext_ln45_16_fu_1305_p1;
wire   [8:0] add_ln45_8_fu_1315_p2;
wire   [8:0] add_ln45_9_fu_1321_p2;
wire   [8:0] add_ln45_10_fu_1340_p2;
wire   [8:0] add_ln45_11_fu_1359_p2;
wire   [7:0] grp_fu_742_p9;
wire   [7:0] grp_fu_761_p9;
wire   [7:0] grp_fu_780_p9;
wire   [7:0] tmp_4_fu_1381_p7;
wire   [7:0] tmp_4_fu_1381_p9;
wire   [7:0] grp_fu_799_p9;
wire   [7:0] grp_fu_818_p9;
wire   [7:0] grp_fu_837_p9;
wire   [7:0] tmp_8_fu_1404_p7;
wire   [7:0] tmp_8_fu_1404_p9;
wire   [7:0] grp_fu_856_p9;
wire   [7:0] grp_fu_875_p9;
wire   [7:0] grp_fu_894_p9;
wire   [7:0] tmp_11_fu_1427_p7;
wire   [7:0] tmp_11_fu_1427_p9;
wire   [7:0] tmp_15_fu_1450_p7;
wire   [7:0] tmp_15_fu_1450_p9;
wire   [7:0] tmp_19_fu_1473_p7;
wire   [7:0] tmp_19_fu_1473_p9;
wire   [7:0] tmp_23_fu_1496_p7;
wire   [7:0] tmp_23_fu_1496_p9;
wire   [8:0] zext_ln42_fu_1492_p1;
wire   [8:0] zext_ln45_8_fu_1469_p1;
wire   [8:0] tmp2_fu_1523_p2;
wire   [9:0] tmp_40_fu_1529_p3;
wire   [8:0] zext_ln45_6_fu_1446_p1;
wire   [8:0] zext_ln45_2_fu_1400_p1;
wire   [8:0] sub_ln45_fu_1541_p2;
wire   [7:0] tmp_27_fu_1551_p7;
wire   [7:0] tmp_27_fu_1551_p9;
wire   [8:0] tmp_27_cast_fu_1570_p1;
wire   [8:0] zext_ln45_3_fu_1423_p1;
wire   [8:0] tmp_fu_1574_p2;
wire   [9:0] tmp_41_fu_1580_p3;
wire   [8:0] add_ln46_fu_1592_p2;
wire   [9:0] tmp_23_cast_fu_1519_p1;
wire   [9:0] zext_ln46_fu_1598_p1;
wire   [9:0] sub_ln46_fu_1602_p2;
wire   [7:0] tmp_31_fu_1612_p7;
wire   [7:0] tmp_31_fu_1612_p9;
wire  signed [10:0] sext_ln42_fu_1547_p1;
wire  signed [10:0] sext_ln45_fu_1537_p1;
wire   [10:0] add_ln45_fu_1635_p2;
wire   [10:0] tmp_23_cast6_fu_1515_p1;
wire   [10:0] px_2_fu_1641_p2;
wire   [10:0] zext_ln45_20_fu_1631_p1;
wire  signed [10:0] px_fu_1647_p2;
wire  signed [10:0] sext_ln46_fu_1588_p1;
wire   [10:0] add_ln46_1_fu_1657_p2;
wire  signed [10:0] sext_ln45_1_fu_1608_p1;
wire  signed [10:0] py_fu_1663_p2;
wire  signed [31:0] sext_ln46_1_fu_1653_p1;
wire   [0:0] tmp_43_fu_1673_p3;
wire   [10:0] sub_ln49_fu_1681_p2;
wire  signed [10:0] select_ln49_fu_1687_p3;
wire  signed [31:0] sext_ln42_1_fu_1669_p1;
wire   [0:0] tmp_44_fu_1699_p3;
wire   [10:0] sub_ln49_1_fu_1707_p2;
wire  signed [10:0] select_ln49_1_fu_1713_p3;
wire  signed [11:0] sext_ln49_fu_1695_p1;
wire  signed [11:0] sext_ln49_1_fu_1721_p1;
wire   [11:0] magnitude_fu_1731_p2;
wire   [10:0] add_ln49_fu_1725_p2;
wire   [11:0] grp_fu_1768_p3;
wire   [0:0] icmp_ln51_fu_1755_p2;
wire   [5:0] grp_fu_1768_p0;
wire   [5:0] grp_fu_1768_p1;
wire   [5:0] grp_fu_1768_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [11:0] grp_fu_1768_p00;
wire   [11:0] grp_fu_1768_p20;
wire   [12:0] mul_ln40_fu_1058_p00;
wire   [12:0] mul_ln41_fu_1100_p00;
wire   [12:0] mul_ln42_fu_1013_p00;
wire   [12:0] mul_ln45_1_fu_1186_p00;
wire   [12:0] mul_ln45_2_fu_1247_p00;
wire   [12:0] mul_ln45_fu_1129_p00;
wire   [1:0] grp_fu_742_p1;
wire  signed [1:0] grp_fu_742_p3;
wire   [1:0] grp_fu_742_p5;
wire   [1:0] grp_fu_761_p1;
wire  signed [1:0] grp_fu_761_p3;
wire   [1:0] grp_fu_761_p5;
wire   [1:0] grp_fu_780_p1;
wire  signed [1:0] grp_fu_780_p3;
wire   [1:0] grp_fu_780_p5;
wire   [1:0] grp_fu_799_p1;
wire   [1:0] grp_fu_799_p3;
wire  signed [1:0] grp_fu_799_p5;
wire   [1:0] grp_fu_818_p1;
wire   [1:0] grp_fu_818_p3;
wire  signed [1:0] grp_fu_818_p5;
wire   [1:0] grp_fu_837_p1;
wire   [1:0] grp_fu_837_p3;
wire  signed [1:0] grp_fu_837_p5;
wire  signed [1:0] grp_fu_856_p1;
wire   [1:0] grp_fu_856_p3;
wire   [1:0] grp_fu_856_p5;
wire  signed [1:0] grp_fu_875_p1;
wire   [1:0] grp_fu_875_p3;
wire   [1:0] grp_fu_875_p5;
wire  signed [1:0] grp_fu_894_p1;
wire   [1:0] grp_fu_894_p3;
wire   [1:0] grp_fu_894_p5;
wire   [1:0] tmp_4_fu_1381_p1;
wire  signed [1:0] tmp_4_fu_1381_p3;
wire   [1:0] tmp_4_fu_1381_p5;
wire   [1:0] tmp_8_fu_1404_p1;
wire  signed [1:0] tmp_8_fu_1404_p3;
wire   [1:0] tmp_8_fu_1404_p5;
wire   [1:0] tmp_11_fu_1427_p1;
wire  signed [1:0] tmp_11_fu_1427_p3;
wire   [1:0] tmp_11_fu_1427_p5;
wire   [1:0] tmp_15_fu_1450_p1;
wire   [1:0] tmp_15_fu_1450_p3;
wire  signed [1:0] tmp_15_fu_1450_p5;
wire   [1:0] tmp_19_fu_1473_p1;
wire   [1:0] tmp_19_fu_1473_p3;
wire  signed [1:0] tmp_19_fu_1473_p5;
wire  signed [1:0] tmp_23_fu_1496_p1;
wire   [1:0] tmp_23_fu_1496_p3;
wire   [1:0] tmp_23_fu_1496_p5;
wire  signed [1:0] tmp_27_fu_1551_p1;
wire   [1:0] tmp_27_fu_1551_p3;
wire   [1:0] tmp_27_fu_1551_p5;
wire  signed [1:0] tmp_31_fu_1612_p1;
wire   [1:0] tmp_31_fu_1612_p3;
wire   [1:0] tmp_31_fu_1612_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 x_fu_96 = 6'd0;
#0 y_fu_100 = 6'd0;
#0 indvar_flatten6_fu_104 = 12'd0;
#0 ap_done_reg = 1'b0;
end

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U21(
    .din0(frame_q0),
    .din1(frame_1_q0),
    .din2(frame_2_q0),
    .def(grp_fu_742_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_742_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U22(
    .din0(frame_3_q0),
    .din1(frame_4_q0),
    .din2(frame_5_q0),
    .def(grp_fu_761_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_761_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U23(
    .din0(frame_6_q0),
    .din1(frame_7_q0),
    .din2(frame_8_q0),
    .def(grp_fu_780_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_780_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U24(
    .din0(frame_q0),
    .din1(frame_1_q0),
    .din2(frame_2_q0),
    .def(grp_fu_799_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_799_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U25(
    .din0(frame_3_q0),
    .din1(frame_4_q0),
    .din2(frame_5_q0),
    .def(grp_fu_818_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_818_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U26(
    .din0(frame_6_q0),
    .din1(frame_7_q0),
    .din2(frame_8_q0),
    .def(grp_fu_837_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_837_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U27(
    .din0(frame_q0),
    .din1(frame_1_q0),
    .din2(frame_2_q0),
    .def(grp_fu_856_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_856_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U28(
    .din0(frame_3_q0),
    .din1(frame_4_q0),
    .din2(frame_5_q0),
    .def(grp_fu_875_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_875_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U29(
    .din0(frame_6_q0),
    .din1(frame_7_q0),
    .din2(frame_8_q0),
    .def(grp_fu_894_p7),
    .sel(trunc_ln41_reg_1846_pp0_iter10_reg),
    .dout(grp_fu_894_p9)
);

sobel_hls_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_991_p0),
    .din1(grp_fu_991_p1),
    .ce(1'b1),
    .dout(grp_fu_991_p2)
);

sobel_hls_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln40_fu_955_p3),
    .din1(grp_fu_1003_p1),
    .ce(1'b1),
    .dout(grp_fu_1003_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U32(
    .din0(mul_ln42_fu_1013_p0),
    .din1(mul_ln42_fu_1013_p1),
    .dout(mul_ln42_fu_1013_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U33(
    .din0(mul_ln40_fu_1058_p0),
    .din1(mul_ln40_fu_1058_p1),
    .dout(mul_ln40_fu_1058_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U34(
    .din0(mul_ln41_fu_1100_p0),
    .din1(mul_ln41_fu_1100_p1),
    .dout(mul_ln41_fu_1100_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U35(
    .din0(mul_ln45_fu_1129_p0),
    .din1(mul_ln45_fu_1129_p1),
    .dout(mul_ln45_fu_1129_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U36(
    .din0(mul_ln45_1_fu_1186_p0),
    .din1(mul_ln45_1_fu_1186_p1),
    .dout(mul_ln45_1_fu_1186_p2)
);

sobel_hls_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U37(
    .din0(mul_ln45_2_fu_1247_p0),
    .din1(mul_ln45_2_fu_1247_p1),
    .dout(mul_ln45_2_fu_1247_p2)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U38(
    .din0(grp_fu_742_p9),
    .din1(grp_fu_761_p9),
    .din2(grp_fu_780_p9),
    .def(tmp_4_fu_1381_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_4_fu_1381_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U39(
    .din0(grp_fu_799_p9),
    .din1(grp_fu_818_p9),
    .din2(grp_fu_837_p9),
    .def(tmp_8_fu_1404_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_8_fu_1404_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U40(
    .din0(grp_fu_856_p9),
    .din1(grp_fu_875_p9),
    .din2(grp_fu_894_p9),
    .def(tmp_11_fu_1427_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_11_fu_1427_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U41(
    .din0(grp_fu_742_p9),
    .din1(grp_fu_761_p9),
    .din2(grp_fu_780_p9),
    .def(tmp_15_fu_1450_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_15_fu_1450_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U42(
    .din0(grp_fu_856_p9),
    .din1(grp_fu_875_p9),
    .din2(grp_fu_894_p9),
    .def(tmp_19_fu_1473_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_19_fu_1473_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U43(
    .din0(grp_fu_742_p9),
    .din1(grp_fu_761_p9),
    .din2(grp_fu_780_p9),
    .def(tmp_23_fu_1496_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_23_fu_1496_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U44(
    .din0(grp_fu_799_p9),
    .din1(grp_fu_818_p9),
    .din2(grp_fu_837_p9),
    .def(tmp_27_fu_1551_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_27_fu_1551_p9)
);

sobel_hls_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U45(
    .din0(grp_fu_856_p9),
    .din1(grp_fu_875_p9),
    .din2(grp_fu_894_p9),
    .def(tmp_31_fu_1612_p7),
    .sel(trunc_ln40_reg_1834_pp0_iter10_reg),
    .dout(tmp_31_fu_1612_p9)
);

sobel_hls_mac_muladd_6ns_6ns_6ns_12_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 12 ))
mac_muladd_6ns_6ns_6ns_12_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1768_p0),
    .din1(grp_fu_1768_p1),
    .din2(grp_fu_1768_p2),
    .ce(1'b1),
    .dout(grp_fu_1768_p3)
);

sobel_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln40_fu_931_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_104 <= add_ln40_fu_937_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_104 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln40_fu_931_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_96 <= add_ln41_fu_997_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_96 <= 6'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln40_fu_931_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            y_fu_100 <= select_ln40_2_fu_983_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            y_fu_100 <= 6'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln41_reg_1818 <= add_ln41_fu_997_p2;
        add_ln41_reg_1818_pp0_iter1_reg <= add_ln41_reg_1818;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln40_2_reg_1810 <= select_ln40_2_fu_983_p3;
        select_ln40_2_reg_1810_pp0_iter1_reg <= select_ln40_2_reg_1810;
        select_ln40_reg_1802 <= select_ln40_fu_955_p3;
        select_ln40_reg_1802_pp0_iter1_reg <= select_ln40_reg_1802;
        tmp_42_reg_1823 <= {{mul_ln42_fu_1013_p2[12:8]}};
        tmp_42_reg_1823_pp0_iter1_reg <= tmp_42_reg_1823;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln41_reg_1818_pp0_iter2_reg <= add_ln41_reg_1818_pp0_iter1_reg;
        add_ln41_reg_1818_pp0_iter3_reg <= add_ln41_reg_1818_pp0_iter2_reg;
        add_ln41_reg_1818_pp0_iter4_reg <= add_ln41_reg_1818_pp0_iter3_reg;
        add_ln41_reg_1818_pp0_iter5_reg <= add_ln41_reg_1818_pp0_iter4_reg;
        add_ln41_reg_1818_pp0_iter6_reg <= add_ln41_reg_1818_pp0_iter5_reg;
        add_ln41_reg_1818_pp0_iter7_reg <= add_ln41_reg_1818_pp0_iter6_reg;
        add_ln41_reg_1818_pp0_iter8_reg <= add_ln41_reg_1818_pp0_iter7_reg;
        add_ln41_reg_1818_pp0_iter9_reg <= add_ln41_reg_1818_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        select_ln40_2_reg_1810_pp0_iter2_reg <= select_ln40_2_reg_1810_pp0_iter1_reg;
        select_ln40_2_reg_1810_pp0_iter3_reg <= select_ln40_2_reg_1810_pp0_iter2_reg;
        select_ln40_2_reg_1810_pp0_iter4_reg <= select_ln40_2_reg_1810_pp0_iter3_reg;
        select_ln40_2_reg_1810_pp0_iter5_reg <= select_ln40_2_reg_1810_pp0_iter4_reg;
        select_ln40_2_reg_1810_pp0_iter6_reg <= select_ln40_2_reg_1810_pp0_iter5_reg;
        select_ln40_2_reg_1810_pp0_iter7_reg <= select_ln40_2_reg_1810_pp0_iter6_reg;
        select_ln40_2_reg_1810_pp0_iter8_reg <= select_ln40_2_reg_1810_pp0_iter7_reg;
        select_ln40_2_reg_1810_pp0_iter9_reg <= select_ln40_2_reg_1810_pp0_iter8_reg;
        select_ln40_reg_1802_pp0_iter10_reg <= select_ln40_reg_1802_pp0_iter9_reg;
        select_ln40_reg_1802_pp0_iter2_reg <= select_ln40_reg_1802_pp0_iter1_reg;
        select_ln40_reg_1802_pp0_iter3_reg <= select_ln40_reg_1802_pp0_iter2_reg;
        select_ln40_reg_1802_pp0_iter4_reg <= select_ln40_reg_1802_pp0_iter3_reg;
        select_ln40_reg_1802_pp0_iter5_reg <= select_ln40_reg_1802_pp0_iter4_reg;
        select_ln40_reg_1802_pp0_iter6_reg <= select_ln40_reg_1802_pp0_iter5_reg;
        select_ln40_reg_1802_pp0_iter7_reg <= select_ln40_reg_1802_pp0_iter6_reg;
        select_ln40_reg_1802_pp0_iter8_reg <= select_ln40_reg_1802_pp0_iter7_reg;
        select_ln40_reg_1802_pp0_iter9_reg <= select_ln40_reg_1802_pp0_iter8_reg;
        tmp_42_reg_1823_pp0_iter2_reg <= tmp_42_reg_1823_pp0_iter1_reg;
        tmp_42_reg_1823_pp0_iter3_reg <= tmp_42_reg_1823_pp0_iter2_reg;
        tmp_42_reg_1823_pp0_iter4_reg <= tmp_42_reg_1823_pp0_iter3_reg;
        tmp_42_reg_1823_pp0_iter5_reg <= tmp_42_reg_1823_pp0_iter4_reg;
        tmp_42_reg_1823_pp0_iter6_reg <= tmp_42_reg_1823_pp0_iter5_reg;
        tmp_42_reg_1823_pp0_iter7_reg <= tmp_42_reg_1823_pp0_iter6_reg;
        tmp_42_reg_1823_pp0_iter8_reg <= tmp_42_reg_1823_pp0_iter7_reg;
        tmp_42_reg_1823_pp0_iter9_reg <= tmp_42_reg_1823_pp0_iter8_reg;
        tmp_45_reg_2224 <= {{magnitude_fu_1731_p2[11:8]}};
        trunc_ln40_reg_1834 <= trunc_ln40_fu_1047_p1;
        trunc_ln40_reg_1834_pp0_iter10_reg <= trunc_ln40_reg_1834;
        trunc_ln41_reg_1846 <= trunc_ln41_fu_1051_p1;
        trunc_ln41_reg_1846_pp0_iter10_reg <= trunc_ln41_reg_1846;
        trunc_ln51_reg_2229 <= trunc_ln51_fu_1747_p1;
    end
end

always @ (*) begin
    if (((icmp_ln40_fu_931_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_load = 6'd1;
    end else begin
        ap_sig_allocacmp_x_load = x_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_y_load = 6'd1;
    end else begin
        ap_sig_allocacmp_y_load = y_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_1_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_1_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_1_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_1_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_1_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_1_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_1_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_1_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_1_address0 = 'bx;
        end
    end else begin
        frame_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_1_ce0 = 1'b1;
    end else begin
        frame_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_2_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_2_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_2_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_2_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_2_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_2_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_2_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_2_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_2_address0 = 'bx;
        end
    end else begin
        frame_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_2_ce0 = 1'b1;
    end else begin
        frame_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_3_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_3_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_3_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_3_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_3_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_3_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_3_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_3_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_3_address0 = 'bx;
        end
    end else begin
        frame_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)))) begin
        frame_3_ce0 = 1'b1;
    end else begin
        frame_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_4_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_4_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_4_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_4_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_4_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_4_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_4_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_4_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_4_address0 = 'bx;
        end
    end else begin
        frame_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_4_ce0 = 1'b1;
    end else begin
        frame_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_5_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_5_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_5_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_5_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_5_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_5_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_5_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_5_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_5_address0 = 'bx;
        end
    end else begin
        frame_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_5_ce0 = 1'b1;
    end else begin
        frame_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_6_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_6_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_6_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_6_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_6_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_6_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_6_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_6_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_6_address0 = 'bx;
        end
    end else begin
        frame_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_6_ce0 = 1'b1;
    end else begin
        frame_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_7_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_7_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_7_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_7_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_7_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_7_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_7_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_7_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_7_address0 = 'bx;
        end
    end else begin
        frame_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_7_ce0 = 1'b1;
    end else begin
        frame_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_8_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_8_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_8_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_8_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_8_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_8_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_8_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_8_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_8_address0 = 'bx;
        end
    end else begin
        frame_8_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_8_ce0 = 1'b1;
    end else begin
        frame_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_address0 = zext_ln45_19_fu_1365_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_address0 = zext_ln45_18_fu_1346_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2))) begin
            frame_address0 = zext_ln45_17_fu_1327_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_address0 = zext_ln45_15_fu_1292_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0))) begin
            frame_address0 = zext_ln45_11_fu_1231_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_address0 = zext_ln45_14_fu_1273_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_address0 = zext_ln45_5_fu_1169_p1;
        end else if (((trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1))) begin
            frame_address0 = zext_ln45_10_fu_1212_p1;
        end else begin
            frame_address0 = 'bx;
        end
    end else begin
        frame_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd2) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd1) & (trunc_ln40_reg_1834 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) 
    & (ap_enable_reg_pp0_iter10 == 1'b1) & (trunc_ln41_reg_1846 == 2'd0) & (trunc_ln40_reg_1834 == 2'd1)))) begin
        frame_ce0 = 1'b1;
    end else begin
        frame_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln4042_fu_969_p2 = (ap_sig_allocacmp_y_load + 6'd1);

assign add_ln40_1_fu_1092_p2 = ($signed(select_ln40_2_reg_1810_pp0_iter9_reg) + $signed(6'd63));

assign add_ln40_2_fu_963_p2 = (ap_sig_allocacmp_y_load + 6'd2);

assign add_ln40_fu_937_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 12'd1);

assign add_ln41_1_fu_1120_p2 = ($signed(select_ln40_reg_1802_pp0_iter9_reg) + $signed(6'd63));

assign add_ln41_fu_997_p2 = (select_ln40_fu_955_p3 + 6'd1);

assign add_ln45_10_fu_1340_p2 = (add_ln45_8_fu_1315_p2 + zext_ln41_1_fu_1116_p1);

assign add_ln45_11_fu_1359_p2 = (add_ln45_8_fu_1315_p2 + zext_ln45_13_fu_1263_p1);

assign add_ln45_1_fu_1086_p2 = (tmp_33_fu_1078_p3 + zext_ln45_fu_1074_p1);

assign add_ln45_2_fu_1157_p2 = (tmp_36_fu_1149_p3 + zext_ln45_4_fu_1145_p1);

assign add_ln45_3_fu_1163_p2 = (add_ln45_2_fu_1157_p2 + zext_ln41_1_fu_1116_p1);

assign add_ln45_4_fu_1206_p2 = (add_ln45_2_fu_1157_p2 + zext_ln45_9_fu_1202_p1);

assign add_ln45_5_fu_1225_p2 = (add_ln45_1_fu_1086_p2 + zext_ln45_9_fu_1202_p1);

assign add_ln45_6_fu_1267_p2 = (add_ln45_2_fu_1157_p2 + zext_ln45_13_fu_1263_p1);

assign add_ln45_7_fu_1286_p2 = (add_ln45_1_fu_1086_p2 + zext_ln45_13_fu_1263_p1);

assign add_ln45_8_fu_1315_p2 = (tmp_39_fu_1308_p3 + zext_ln45_16_fu_1305_p1);

assign add_ln45_9_fu_1321_p2 = (add_ln45_8_fu_1315_p2 + zext_ln45_9_fu_1202_p1);

assign add_ln45_fu_1635_p2 = ($signed(sext_ln42_fu_1547_p1) + $signed(sext_ln45_fu_1537_p1));

assign add_ln46_1_fu_1657_p2 = ($signed(sext_ln46_fu_1588_p1) + $signed(zext_ln45_20_fu_1631_p1));

assign add_ln46_fu_1592_p2 = (zext_ln45_6_fu_1446_p1 + zext_ln45_2_fu_1400_p1);

assign add_ln49_fu_1725_p2 = ($signed(select_ln49_fu_1687_p3) + $signed(select_ln49_1_fu_1713_p3));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_1003_p1 = 6'd3;

assign grp_fu_1768_p0 = grp_fu_1768_p00;

assign grp_fu_1768_p00 = select_ln40_2_reg_1810_pp0_iter8_reg;

assign grp_fu_1768_p1 = 12'd50;

assign grp_fu_1768_p2 = grp_fu_1768_p20;

assign grp_fu_1768_p20 = select_ln40_reg_1802_pp0_iter10_reg;

assign grp_fu_742_p7 = 'bx;

assign grp_fu_761_p7 = 'bx;

assign grp_fu_780_p7 = 'bx;

assign grp_fu_799_p7 = 'bx;

assign grp_fu_818_p7 = 'bx;

assign grp_fu_837_p7 = 'bx;

assign grp_fu_856_p7 = 'bx;

assign grp_fu_875_p7 = 'bx;

assign grp_fu_894_p7 = 'bx;

assign grp_fu_991_p0 = ((icmp_ln41_fu_949_p2[0:0] == 1'b1) ? add_ln4042_fu_969_p2 : ap_sig_allocacmp_y_load);

assign grp_fu_991_p1 = 6'd3;

assign icmp_ln40_fu_931_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 12'd2304) ? 1'b1 : 1'b0);

assign icmp_ln41_fu_949_p2 = ((ap_sig_allocacmp_x_load == 6'd49) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_1755_p2 = (($signed(tmp_45_reg_2224) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign magnitude_fu_1731_p2 = ($signed(sext_ln49_fu_1695_p1) + $signed(sext_ln49_1_fu_1721_p1));

assign mul_ln40_fu_1058_p0 = mul_ln40_fu_1058_p00;

assign mul_ln40_fu_1058_p00 = select_ln40_2_reg_1810_pp0_iter9_reg;

assign mul_ln40_fu_1058_p1 = 13'd86;

assign mul_ln41_fu_1100_p0 = mul_ln41_fu_1100_p00;

assign mul_ln41_fu_1100_p00 = select_ln40_reg_1802_pp0_iter9_reg;

assign mul_ln41_fu_1100_p1 = 13'd86;

assign mul_ln42_fu_1013_p0 = mul_ln42_fu_1013_p00;

assign mul_ln42_fu_1013_p00 = select_ln40_1_fu_975_p3;

assign mul_ln42_fu_1013_p1 = 13'd86;

assign mul_ln45_1_fu_1186_p0 = mul_ln45_1_fu_1186_p00;

assign mul_ln45_1_fu_1186_p00 = add_ln41_1_fu_1120_p2;

assign mul_ln45_1_fu_1186_p1 = 13'd86;

assign mul_ln45_2_fu_1247_p0 = mul_ln45_2_fu_1247_p00;

assign mul_ln45_2_fu_1247_p00 = add_ln41_reg_1818_pp0_iter9_reg;

assign mul_ln45_2_fu_1247_p1 = 13'd86;

assign mul_ln45_fu_1129_p0 = mul_ln45_fu_1129_p00;

assign mul_ln45_fu_1129_p00 = add_ln40_1_fu_1092_p2;

assign mul_ln45_fu_1129_p1 = 13'd86;

assign output_r_address0 = zext_ln51_2_fu_1751_p1;

assign output_r_d0 = ((icmp_ln51_fu_1755_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln51_reg_2229);

assign px_2_fu_1641_p2 = (add_ln45_fu_1635_p2 - tmp_23_cast6_fu_1515_p1);

assign px_fu_1647_p2 = (px_2_fu_1641_p2 + zext_ln45_20_fu_1631_p1);

assign py_fu_1663_p2 = ($signed(add_ln46_1_fu_1657_p2) + $signed(sext_ln45_1_fu_1608_p1));

assign select_ln40_1_fu_975_p3 = ((icmp_ln41_fu_949_p2[0:0] == 1'b1) ? add_ln40_2_fu_963_p2 : add_ln4042_fu_969_p2);

assign select_ln40_2_fu_983_p3 = ((icmp_ln41_fu_949_p2[0:0] == 1'b1) ? add_ln4042_fu_969_p2 : ap_sig_allocacmp_y_load);

assign select_ln40_fu_955_p3 = ((icmp_ln41_fu_949_p2[0:0] == 1'b1) ? 6'd1 : ap_sig_allocacmp_x_load);

assign select_ln49_1_fu_1713_p3 = ((tmp_44_fu_1699_p3[0:0] == 1'b1) ? sub_ln49_1_fu_1707_p2 : py_fu_1663_p2);

assign select_ln49_fu_1687_p3 = ((tmp_43_fu_1673_p3[0:0] == 1'b1) ? sub_ln49_fu_1681_p2 : px_fu_1647_p2);

assign sext_ln42_1_fu_1669_p1 = py_fu_1663_p2;

assign sext_ln42_fu_1547_p1 = $signed(sub_ln45_fu_1541_p2);

assign sext_ln45_1_fu_1608_p1 = $signed(sub_ln46_fu_1602_p2);

assign sext_ln45_fu_1537_p1 = $signed(tmp_40_fu_1529_p3);

assign sext_ln46_1_fu_1653_p1 = px_fu_1647_p2;

assign sext_ln46_fu_1588_p1 = $signed(tmp_41_fu_1580_p3);

assign sext_ln49_1_fu_1721_p1 = select_ln49_1_fu_1713_p3;

assign sext_ln49_fu_1695_p1 = select_ln49_fu_1687_p3;

assign sub_ln45_fu_1541_p2 = (zext_ln45_6_fu_1446_p1 - zext_ln45_2_fu_1400_p1);

assign sub_ln46_fu_1602_p2 = (tmp_23_cast_fu_1519_p1 - zext_ln46_fu_1598_p1);

assign sub_ln49_1_fu_1707_p2 = ($signed(11'd0) - $signed(py_fu_1663_p2));

assign sub_ln49_fu_1681_p2 = ($signed(11'd0) - $signed(px_fu_1647_p2));

assign tmp2_fu_1523_p2 = (zext_ln42_fu_1492_p1 - zext_ln45_8_fu_1469_p1);

assign tmp_11_fu_1427_p7 = 'bx;

assign tmp_15_fu_1450_p7 = 'bx;

assign tmp_19_fu_1473_p7 = 'bx;

assign tmp_23_cast6_fu_1515_p1 = tmp_23_fu_1496_p9;

assign tmp_23_cast_fu_1519_p1 = tmp_23_fu_1496_p9;

assign tmp_23_fu_1496_p7 = 'bx;

assign tmp_27_cast_fu_1570_p1 = tmp_27_fu_1551_p9;

assign tmp_27_fu_1551_p7 = 'bx;

assign tmp_31_fu_1612_p7 = 'bx;

assign tmp_32_fu_1064_p4 = {{mul_ln40_fu_1058_p2[12:8]}};

assign tmp_33_fu_1078_p3 = {{tmp_32_fu_1064_p4}, {4'd0}};

assign tmp_34_fu_1106_p4 = {{mul_ln41_fu_1100_p2[12:8]}};

assign tmp_35_fu_1135_p4 = {{mul_ln45_fu_1129_p2[12:8]}};

assign tmp_36_fu_1149_p3 = {{tmp_35_fu_1135_p4}, {4'd0}};

assign tmp_37_fu_1192_p4 = {{mul_ln45_1_fu_1186_p2[12:8]}};

assign tmp_38_fu_1253_p4 = {{mul_ln45_2_fu_1247_p2[12:8]}};

assign tmp_39_fu_1308_p3 = {{tmp_42_reg_1823_pp0_iter9_reg}, {4'd0}};

assign tmp_40_fu_1529_p3 = {{tmp2_fu_1523_p2}, {1'd0}};

assign tmp_41_fu_1580_p3 = {{tmp_fu_1574_p2}, {1'd0}};

assign tmp_43_fu_1673_p3 = sext_ln46_1_fu_1653_p1[32'd31];

assign tmp_44_fu_1699_p3 = sext_ln42_1_fu_1669_p1[32'd31];

assign tmp_4_fu_1381_p7 = 'bx;

assign tmp_8_fu_1404_p7 = 'bx;

assign tmp_fu_1574_p2 = (tmp_27_cast_fu_1570_p1 - zext_ln45_3_fu_1423_p1);

assign trunc_ln40_fu_1047_p1 = grp_fu_991_p2[1:0];

assign trunc_ln41_fu_1051_p1 = grp_fu_1003_p2[1:0];

assign trunc_ln51_fu_1747_p1 = add_ln49_fu_1725_p2[7:0];

assign zext_ln41_1_fu_1116_p1 = tmp_34_fu_1106_p4;

assign zext_ln42_fu_1492_p1 = tmp_19_fu_1473_p9;

assign zext_ln45_10_fu_1212_p1 = add_ln45_4_fu_1206_p2;

assign zext_ln45_11_fu_1231_p1 = add_ln45_5_fu_1225_p2;

assign zext_ln45_13_fu_1263_p1 = tmp_38_fu_1253_p4;

assign zext_ln45_14_fu_1273_p1 = add_ln45_6_fu_1267_p2;

assign zext_ln45_15_fu_1292_p1 = add_ln45_7_fu_1286_p2;

assign zext_ln45_16_fu_1305_p1 = tmp_42_reg_1823_pp0_iter9_reg;

assign zext_ln45_17_fu_1327_p1 = add_ln45_9_fu_1321_p2;

assign zext_ln45_18_fu_1346_p1 = add_ln45_10_fu_1340_p2;

assign zext_ln45_19_fu_1365_p1 = add_ln45_11_fu_1359_p2;

assign zext_ln45_20_fu_1631_p1 = tmp_31_fu_1612_p9;

assign zext_ln45_2_fu_1400_p1 = tmp_4_fu_1381_p9;

assign zext_ln45_3_fu_1423_p1 = tmp_8_fu_1404_p9;

assign zext_ln45_4_fu_1145_p1 = tmp_35_fu_1135_p4;

assign zext_ln45_5_fu_1169_p1 = add_ln45_3_fu_1163_p2;

assign zext_ln45_6_fu_1446_p1 = tmp_11_fu_1427_p9;

assign zext_ln45_8_fu_1469_p1 = tmp_15_fu_1450_p9;

assign zext_ln45_9_fu_1202_p1 = tmp_37_fu_1192_p4;

assign zext_ln45_fu_1074_p1 = tmp_32_fu_1064_p4;

assign zext_ln46_fu_1598_p1 = add_ln46_fu_1592_p2;

assign zext_ln51_2_fu_1751_p1 = grp_fu_1768_p3;

endmodule //sobel_hls_sobel_hls_Pipeline_VITIS_LOOP_40_3_VITIS_LOOP_41_4
